name: Deploy Resume to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Prepare Deployment Directory
        run: |
          mkdir -p _site
          
          # Copy entire project structure to preserve assets
          cp -r css _site/
          cp -r js _site/
          cp -r icon _site/
          cp -r img _site/
          
          # Modify HTML to use relative paths
          sed -i 's|href="css/|href="/css/|g' paste.txt
          sed -i 's|href="https://fonts.googleapis.com|href="//fonts.googleapis.com|g' paste.txt
          sed -i 's|src="css/|src="/css/|g' paste.txt
          sed -i 's|src="js/|src="/js/|g' paste.txt
          sed -i 's|src="img/|src="/img/|g' paste.txt
          sed -i 's|src="icon/|src="/icon/|g' paste.txt
          
          # Copy modified HTML
          cp paste.txt _site/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: '_site'
          retention-days: 1
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
