name: Deploy Resume to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Prepare Deployment Directory
        run: |
          mkdir -p _site
          
          # Copy only essential files
          cp *.html _site/index.html
          
          # Create minimal directories
          mkdir -p _site/css _site/js _site/icon _site/img
          
          # Copy minimal CSS files (only necessary ones)
          cp css/bootstrap.min.css _site/css/ 2>/dev/null || true
          cp css/c.css _site/css/ 2>/dev/null || true
          
          # Copy minimal JS files
          cp js/jquery-3.4.1.min.js _site/js/ 2>/dev/null || true
          cp js/bootstrap.min.js _site/js/ 2>/dev/null || true
          cp js/main.js _site/js/ 2>/dev/null || true
          
          # Copy minimal images and icons
          find img -maxdepth 1 \( -name "meiyi.jpg" -o -name "*.png" \) -exec cp {} _site/img/ \; 2>/dev/null
          find icon -maxdepth 1 \( -name "*.png" -o -name "*.svg" \) -exec cp {} _site/icon/ \; 2>/dev/null
          
          # Modify HTML to use relative paths
          sed -i 's|href="css/|href="/css/|g' _site/index.html
          sed -i 's|href="https://fonts.googleapis.com|href="//fonts.googleapis.com|g' _site/index.html
          sed -i 's|src="css/|src="/css/|g' _site/index.html
          sed -i 's|src="js/|src="/js/|g' _site/index.html
          sed -i 's|src="img/|src="/img/|g' _site/index.html
          sed -i 's|src="icon/|src="/icon/|g' _site/index.html
          
          # Remove any sensitive information
          sed -i '/ghp_/d' _site/index.html
          
          # List contents and size
          ls -lR _site
          du -sh _site
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: '_site'
          retention-days: 1
          compression-level: 9
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
