name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Deployment Directory
        run: |
          # Create a deployment directory
          mkdir -p _site

          # Copy index.html and other static assets
          cp index.html _site/
          cp -r css/ _site/css/ || echo "No CSS directory found"
          cp -r js/ _site/js/ || echo "No JS directory found"
          cp -r img/ _site/img/ || echo "No images directory found"
          cp -r icon/ _site/icon/ || echo "No icons directory found"

          # Debug: List the contents of the _site directory
          ls -R _site

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
